<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActivityIncomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActivityIncomeRepository extends EntityRepository
{
}
